language: php

php:
  - 5.4
  - 5.5

env:
  - PREFER_STABLE="true"
  - PREFER_STABLE="false"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-stable ${PREFER_STABLE}

script: phpunit
